### ISSUE TITLE
function ppc [survival]

### ISSUE THREAD

**Issue by philipperuiz** [pveber/morse#128] opened 2015-09-10 15:16 UTC
The reproduction part was checked and accepted by ML.
For the survival part, the calcul was correct but we need to find a reprosantation for the overlapped segments. => jitter.
#74 #89

**Comment by pveber** [comment] 2015-09-13 12:36
I have merged PR #89, but I think there is still work to do on this. First I split the function `ppc` into S3 methods. Second I changed the representation a bit, by replacing the y = x curve by a stair to avoid green intervals that wouldn't hit the diagonal because of jittering. This is much better for survival (low counts) but maybe not so great for reproduction (high counts). What remains to be done:
- [ ] doc for the generic ppc function
- [ ] update doc for ppc.survFitTT
- [ ] update doc for ppc.survFitTT
- [ ] choose between diagonal and stairs based on the input data
- [ ] replace jitter by uniformly-spaced positions
- [ ] update ggplot version to match generic

**Closed** 2015-10-27 11:34 UTC
